//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Student.proto
namespace Student
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"student_data")]
  public partial class student_data : global::ProtoBuf.IExtensible
  {
    public student_data() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _age = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int age
    {
      get { return _age; }
      set { _age = value; }
    }
    private bool _sex = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _contry = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"contry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contry
    {
      get { return _contry; }
      set { _contry = value; }
    }
    private int _grade = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}